-- Starter content: categories and 22 sample recipes from the prototype.
-- Safe to delete any of these once your own recipes are in.

insert into public.categories (id, name, emoji, tagline, sort_order) values
  ('breakfast', 'Breakfast', '🥞', 'Rise and shine, it''s pancake time.', 0),
  ('breads', 'Breads & bakes', '🍞', 'Let''s get this bread.', 1),
  ('snacks', 'Snacks & smoothies', '🥤', 'Quick bites for peel-good moments.', 2),
  ('desserts', 'Desserts', '🍰', 'Split happens. Might as well be a banana split.', 3),
  ('frozen', 'Frozen treats', '🍨', 'Stay cool. Stay peeled.', 4),
  ('savory', 'Savory', '🌶️', 'Plot twist: bananas do dinner.', 5)
on conflict (id) do nothing;

insert into public.recipes (slug, title, description, categories, emoji, total_minutes, time_note, servings, difficulty, tags, ingredients, steps, status) values
  ('fluffy-banana-pancakes', 'Fluffy banana pancakes', 'Tall, tender stacks with mashed banana right in the batter. Weekend mornings, solved.', array['breakfast']::text[], '🥞', 25, null, 4, 2, array['kid-friendly']::text[], array['2 ripe bananas, mashed', '1 1/2 cups flour', '1 tbsp baking powder', '1 egg', '1 1/4 cups milk', '2 tbsp melted butter', 'Pinch of salt']::text[], '[{"text": "Whisk the flour, baking powder, and salt in a bowl."}, {"text": "In another bowl, whisk the mashed bananas with egg, milk, and melted butter."}, {"text": "Fold wet into dry until just combined. A few lumps are fine."}, {"text": "Cook 1/4-cup scoops on a buttered pan over medium heat until bubbles form, flip, and cook 1 more minute."}]'::jsonb, 'published'),
  ('banana-oat-muffins', 'Banana oat muffins', 'Hearty, lightly sweet, and freezer-friendly. Grab one on the way out the door.', array['breakfast']::text[], '🧁', 35, null, 12, 2, array['kid-friendly']::text[], array['3 ripe bananas', '1 1/2 cups rolled oats', '1 cup flour', '1/3 cup maple syrup', '2 eggs', '1/3 cup oil', '1 tsp baking soda']::text[], '[{"text": "Heat oven to 375°F (190°C) and line a 12-cup muffin tin."}, {"text": "Mash the bananas and whisk in eggs, maple syrup, and oil."}, {"text": "Stir in oats, flour, baking soda, and a pinch of salt until just combined."}, {"text": "Divide into the cups and bake 18 to 22 minutes, until a toothpick comes out clean."}]'::jsonb, 'published'),
  ('cinnamon-banana-waffles', 'Cinnamon banana waffles', 'Crisp outside, custardy inside, and fragrant with cinnamon. Syrup optional.', array['breakfast']::text[], '🧇', 25, null, 4, 2, array['kid-friendly']::text[], array['2 ripe bananas', '2 cups flour', '2 tsp baking powder', '2 eggs', '1 1/2 cups milk', '1/3 cup melted butter', '1 tsp cinnamon']::text[], '[{"text": "Preheat your waffle iron."}, {"text": "Whisk the flour, baking powder, and cinnamon."}, {"text": "Mash the bananas and whisk with eggs, milk, and melted butter, then fold into the dry mix."}, {"text": "Cook in the waffle iron until golden and crisp."}]'::jsonb, 'published'),
  ('banana-oat-breakfast-cookies', 'Banana oat breakfast cookies', 'Just bananas, oats, and a few mix-ins. Cookies you''re allowed to eat at 8 a.m.', array['breakfast']::text[], '🍪', 20, null, 12, 1, array['vegan', 'gluten-free', 'no added sugar']::text[], array['2 ripe bananas', '1 1/2 cups rolled oats (certified GF if needed)', '1/4 cup peanut butter', '1/3 cup raisins or chocolate chips', '1/2 tsp cinnamon']::text[], '[{"text": "Heat oven to 350°F (175°C) and line a baking sheet."}, {"text": "Mash the bananas and stir in oats, peanut butter, cinnamon, and mix-ins."}, {"text": "Scoop 12 mounds and flatten slightly, since they won''t spread."}, {"text": "Bake 12 to 15 minutes until set and golden at the edges."}]'::jsonb, 'published'),
  ('banana-bread-baked-oatmeal', 'Banana bread baked oatmeal', 'All the cozy flavor of banana bread, scoopable and ready for the week''s breakfasts.', array['breakfast']::text[], '🥣', 45, null, 6, 1, array['gluten-free', 'kid-friendly']::text[], array['3 very ripe bananas', '2 cups rolled oats', '1 1/2 cups milk', '1 egg', '2 tbsp maple syrup', '1 tsp cinnamon', '1 tsp baking powder', 'Chopped walnuts']::text[], '[{"text": "Heat oven to 375°F (190°C) and grease an 8x8 dish."}, {"text": "Mash the bananas and whisk in milk, egg, maple syrup, cinnamon, and baking powder."}, {"text": "Stir in the oats, pour into the dish, and top with walnuts."}, {"text": "Bake 35 to 40 minutes until set. Keeps 4 days in the fridge."}]'::jsonb, 'published'),
  ('classic-banana-bread', 'Classic banana bread', 'The one. Moist, golden, and exactly what brown bananas were born to become.', array['breads']::text[], '🍞', 70, null, 10, 2, array['kid-friendly']::text[], array['3 very ripe bananas', '1/3 cup melted butter', '3/4 cup sugar', '1 egg', '1 tsp vanilla', '1 tsp baking soda', '1 1/2 cups flour', 'Pinch of salt']::text[], '[{"text": "Heat oven to 350°F (175°C) and grease a 9x5 loaf pan."}, {"text": "Mash the bananas, then stir in melted butter, sugar, egg, and vanilla."}, {"text": "Sprinkle in baking soda and salt, then fold in the flour until just combined."}, {"text": "Bake 55 to 65 minutes until a toothpick comes out clean. Cool 10 minutes before slicing."}]'::jsonb, 'published'),
  ('chocolate-chip-banana-bread', 'Chocolate chip banana bread', 'Everything you love about the classic, with melty chocolate in every slice.', array['breads']::text[], '🍫', 70, null, 10, 2, array['kid-friendly']::text[], array['3 very ripe bananas', '1/3 cup melted butter', '3/4 cup sugar', '1 egg', '1 tsp vanilla', '1 tsp baking soda', '1 1/2 cups flour', '3/4 cup chocolate chips']::text[], '[{"text": "Heat oven to 350°F (175°C) and grease a 9x5 loaf pan."}, {"text": "Mash the bananas and stir in butter, sugar, egg, and vanilla."}, {"text": "Stir in baking soda and a pinch of salt, fold in the flour, then fold in most of the chips."}, {"text": "Scatter the rest on top and bake 55 to 65 minutes until a toothpick comes out clean."}]'::jsonb, 'published'),
  ('brown-butter-walnut-banana-bread', 'Brown butter walnut banana bread', 'Nutty browned butter and toasted walnuts take banana bread somewhere fancy.', array['breads']::text[], '🧈', 80, null, 10, 3, '{}'::text[], array['3 very ripe bananas', '1/2 cup butter', '3/4 cup brown sugar', '2 eggs', '1 tsp vanilla', '1 3/4 cups flour', '1 tsp baking soda', '1/2 cup toasted walnuts']::text[], '[{"text": "Melt the butter in a light-colored pan and cook, swirling, until it smells nutty and turns golden. Cool 10 minutes."}, {"text": "Heat oven to 350°F (175°C) and grease a loaf pan."}, {"text": "Whisk the browned butter with brown sugar, eggs, vanilla, and mashed bananas."}, {"text": "Fold in flour, baking soda, a pinch of salt, and the walnuts."}, {"text": "Bake 55 to 65 minutes until a toothpick comes out clean."}]'::jsonb, 'published'),
  ('vegan-banana-bread', 'Vegan banana bread', 'No eggs, no butter, no problem. Ripe bananas do all the binding.', array['breads']::text[], '🌱', 65, null, 10, 2, array['vegan', 'dairy-free']::text[], array['3 very ripe bananas', '1/3 cup oil', '1/2 cup brown sugar', '1/4 cup plant milk', '1 tsp baking soda', '1 3/4 cups flour', '1 tsp cinnamon']::text[], '[{"text": "Heat oven to 350°F (175°C) and grease a loaf pan."}, {"text": "Mash the bananas and whisk in oil, brown sugar, and plant milk."}, {"text": "Fold in flour, baking soda, cinnamon, and a pinch of salt until just combined."}, {"text": "Bake 50 to 60 minutes until a toothpick comes out clean."}]'::jsonb, 'published'),
  ('peanut-butter-banana-smoothie', 'Peanut butter banana smoothie', 'Thick, creamy, and tastes like dessert. Breakfast in five minutes flat.', array['snacks']::text[], '🥤', 5, null, 1, 1, array['kid-friendly', 'gluten-free', 'quick']::text[], array['1 ripe banana', '2 tbsp peanut butter', '1 cup milk', '1/2 cup ice', '1 tsp honey']::text[], '[{"text": "Add everything to a blender."}, {"text": "Blend until thick and smooth, about 45 seconds."}, {"text": "Taste, add more honey if you like, and drink right away."}]'::jsonb, 'published'),
  ('banana-sushi-rolls', 'Banana sushi rolls', 'Nut butter, a tortilla, and a banana rolled up and sliced into little ''maki''. Kids go wild.', array['snacks']::text[], '🍣', 10, null, 2, 1, array['kid-friendly', 'quick']::text[], array['2 bananas', '2 flour tortillas', '3 tbsp nut butter', '1 tbsp honey', 'Granola or sprinkles']::text[], '[{"text": "Spread nut butter over each tortilla and drizzle with honey."}, {"text": "Lay a banana at one edge and roll it up tightly."}, {"text": "Slice into 1-inch rounds and top with granola or sprinkles."}]'::jsonb, 'published'),
  ('cinnamon-banana-coins', 'Cinnamon banana coins', 'Coins of banana caramelized in butter and cinnamon sugar. Spoon over oatmeal or yogurt.', array['snacks']::text[], '🪙', 10, null, 2, 1, array['gluten-free', 'kid-friendly', 'quick']::text[], array['2 bananas, sliced', '1 tbsp butter', '1 tbsp brown sugar', '1/2 tsp cinnamon', 'Pinch of salt']::text[], '[{"text": "Melt the butter in a skillet over medium heat."}, {"text": "Add the banana coins in one layer and sprinkle with sugar, cinnamon, and salt."}, {"text": "Cook about 2 minutes per side until caramelized. Serve warm."}]'::jsonb, 'published'),
  ('salt-and-vinegar-banana-chips', 'Salt and vinegar banana chips', 'Paper-thin slices soaked in vinegar, then baked until they shatter. Dangerously snackable.', array['snacks']::text[], '🥔', 60, null, 4, 2, array['vegan', 'gluten-free']::text[], array['3 green bananas', '1 cup white vinegar', '2 tbsp oil', '1 tsp flaky salt']::text[], '[{"text": "Slice the bananas paper-thin with a mandoline and soak in vinegar for 30 minutes."}, {"text": "Heat oven to 350°F (175°C) and line a baking sheet."}, {"text": "Drain, pat the slices very dry, and toss with oil."}, {"text": "Bake 15 to 20 minutes, flipping once, then salt while warm. They crisp as they cool."}]'::jsonb, 'published'),
  ('bananas-foster', 'Bananas Foster', 'New Orleans'' famous flambé: bananas in bubbling butterscotch sauce over ice cream.', array['desserts']::text[], '🔥', 15, null, 4, 3, array['gluten-free']::text[], array['4 bananas, halved lengthwise', '1/4 cup butter', '1/2 cup brown sugar', '1/2 tsp cinnamon', '1/4 cup dark rum (optional)', 'Vanilla ice cream']::text[], '[{"text": "Melt the butter, brown sugar, and cinnamon in a wide pan until bubbling."}, {"text": "Add the bananas and cook 1 to 2 minutes per side."}, {"text": "If using rum, take the pan off the heat, add it, then simmer 1 minute to cook it off (or carefully flambé with a long lighter)."}, {"text": "Spoon the bananas and sauce over ice cream."}]'::jsonb, 'published'),
  ('banana-cake-with-cream-cheese-frosting', 'Banana cake with cream cheese frosting', 'Soft, tender sheet cake with tangy frosting. The darker the bananas, the better it gets.', array['desserts']::text[], '🎂', 75, null, 12, 3, '{}'::text[], array['3 very ripe bananas', '2 cups flour', '1 tsp baking soda', '1/2 cup butter, softened', '1 cup sugar', '2 eggs', '1/2 cup buttermilk', 'Cream cheese frosting']::text[], '[{"text": "Heat oven to 350°F (175°C) and grease a 9x13 pan."}, {"text": "Beat the butter and sugar until fluffy, then beat in the eggs one at a time."}, {"text": "Mix in the mashed bananas, then add flour and baking soda alternately with the buttermilk."}, {"text": "Bake 30 to 35 minutes, cool completely, and spread with frosting."}]'::jsonb, 'published'),
  ('hummingbird-cake', 'Hummingbird cake', 'A Southern showstopper packed with banana, pineapple, and pecans. Worth every minute.', array['desserts']::text[], '🍰', 90, null, 16, 4, '{}'::text[], array['2 cups mashed very ripe bananas', '1 can (8 oz) crushed pineapple', '3 cups flour', '2 cups sugar', '1 tsp baking soda', '1 tsp cinnamon', '1 cup oil', '3 eggs', '1 cup chopped pecans', 'Cream cheese frosting']::text[], '[{"text": "Heat oven to 350°F (175°C) and grease three 9-inch cake pans."}, {"text": "Whisk the flour, sugar, baking soda, cinnamon, and 1 tsp salt."}, {"text": "Stir in oil, eggs, bananas, undrained pineapple, and pecans until just combined."}, {"text": "Divide among the pans and bake 25 to 30 minutes. Cool completely, then stack and frost."}]'::jsonb, 'published'),
  ('one-ingredient-nice-cream', 'One-ingredient nice cream', 'Frozen bananas blend into soft-serve. Honestly, it feels like a magic trick.', array['frozen']::text[], '🍨', 5, '5 min + freezing', 2, 1, array['vegan', 'gluten-free', 'no added sugar']::text[], array['3 very ripe bananas, sliced and frozen', 'Optional: cocoa powder, peanut butter, or a pinch of salt']::text[], '[{"text": "Peel, slice, and freeze the bananas for at least 4 hours."}, {"text": "Blend in a food processor, scraping down often. It looks crumbly, then suddenly turns creamy."}, {"text": "Add any mix-ins and blend again. Eat as soft-serve or freeze 1 hour to scoop."}]'::jsonb, 'published'),
  ('banana-yogurt-pops', 'Banana yogurt pops', 'Creamy frozen pops for hot afternoons. Overripe bananas make them extra sweet.', array['frozen']::text[], '🧊', 10, '10 min + freezing', 6, 1, array['kid-friendly', 'gluten-free']::text[], array['2 very ripe bananas', '1 1/2 cups Greek yogurt', '2 tbsp honey', '1/2 tsp vanilla']::text[], '[{"text": "Blend the bananas, yogurt, honey, and vanilla until smooth."}, {"text": "Pour into ice pop molds and add sticks."}, {"text": "Freeze at least 5 hours. Run the molds under warm water to release."}]'::jsonb, 'published'),
  ('crispy-green-banana-fries', 'Crispy green banana fries', 'Starchy green bananas crisp up just like potatoes. Smoky, salty, and gone in minutes.', array['savory']::text[], '🍟', 30, null, 2, 2, array['vegan', 'gluten-free']::text[], array['3 green bananas', '2 tbsp neutral oil', '1/2 tsp smoked paprika', '1/2 tsp garlic powder', 'Flaky salt', 'Lime wedges']::text[], '[{"text": "Heat oven to 425°F (220°C) and line a baking sheet."}, {"text": "Peel the green bananas (score the skin lengthwise and pry it off) and cut into fries."}, {"text": "Toss with oil, paprika, garlic powder, and salt."}, {"text": "Roast 20 to 25 minutes, flipping halfway, until golden and crisp. Serve with lime wedges."}]'::jsonb, 'published'),
  ('green-banana-coconut-curry', 'Green banana coconut curry', 'A Kerala-style curry where green bananas soak up coconut milk and warm spices.', array['savory']::text[], '🍛', 35, null, 4, 3, array['vegan', 'gluten-free']::text[], array['3 green bananas, peeled and cubed', '1 cup coconut milk', '1 onion, sliced', '2 tsp curry powder', '1 tsp mustard seeds', '1/2 tsp turmeric', 'A handful of curry leaves', '2 tbsp oil']::text[], '[{"text": "Keep the cubed bananas in salted water so they don''t darken."}, {"text": "Heat oil, pop the mustard seeds, then add curry leaves and onion and cook until soft."}, {"text": "Stir in curry powder and turmeric for a minute, then add the drained bananas and 1/2 cup water."}, {"text": "Cover and simmer 10 minutes, pour in coconut milk, and simmer 5 more. Season with salt."}]'::jsonb, 'published'),
  ('guineos-en-escabeche', 'Guineos en escabeche', 'A Puerto Rican classic: tender green bananas marinated in garlicky olive oil and vinegar.', array['savory']::text[], '🥗', 40, '40 min + marinating', 6, 3, array['vegan', 'gluten-free']::text[], array['6 green bananas', '1 red onion, sliced', '1/2 cup olive oil', '1/4 cup white vinegar', '2 garlic cloves, smashed', '2 bay leaves', '1 tsp black peppercorns', 'Green olives (optional)']::text[], '[{"text": "Boil the unpeeled bananas in salted water 15 to 20 minutes until tender, then peel and slice into coins."}, {"text": "Warm the olive oil with onion, garlic, bay leaves, and peppercorns over low heat for 10 minutes."}, {"text": "Take off the heat and stir in the vinegar and a good pinch of salt."}, {"text": "Pour over the bananas, add olives if using, and marinate at least an hour. Overnight is even better."}]'::jsonb, 'published'),
  ('tropical-banana-salsa', 'Tropical banana salsa', 'Sweet banana meets pineapple, jalapeño, and lime. Unreal on fish tacos.', array['savory']::text[], '🌮', 15, null, 4, 1, array['vegan', 'gluten-free', 'quick']::text[], array['2 firm-ripe bananas, diced', '1 cup diced pineapple', '1/4 red onion, minced', '1 jalapeño, minced', 'Handful of cilantro, chopped', 'Juice of 1 lime']::text[], '[{"text": "Dice the bananas and pineapple into small, even pieces."}, {"text": "Combine with onion, jalapeño, and cilantro."}, {"text": "Add lime juice and a pinch of salt and toss gently. Serve within an hour."}]'::jsonb, 'published')
on conflict (slug) do nothing;
